# Sunburst Configuration 0.1 #
storage:
  # Valid storage types as of this version are: file
  type: file

options:
  # Enable/Disable Sunburst's chat listening
  chat: true
  # If the player should be teleported to the world spawn on join
  auto-spawn: true
  # If set, the player will spawn in this world automatically at its set spawn location, and if the world
  # does not exist, they will spawn at the world they're in's spawn point
  global-spawn-world: "flatlands"